version: '3.4'

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    image: quadocontaineregistry.azurecr.io/quado-frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    # volumes:
    #  - quado-volume:/mount/quadovolumes
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    image: quadocontaineregistry.azurecr.io/quado-backend
    ports:
      - 8080:8080
    # volumes:
    #   - quado-volume:/mount/quadovolumes


# volumes:
#   mydata:
#     driver: azure_file
#     driver_opts:
#       share_name: quadofileshare
#       storage_account_name: quadostorageaccount




# services:
#   frontend:
#     image: awesome/webapp
#     build: ./webapp

#   backend:
#     image: awesome/database
#     build:
#         context: backend
#         dockerfile: ../backend.Dockerfile

#   custom:
#     build: ~/custom