version: 2.1
orbs:
    heroku: circleci/heroku@1.2.6 # Invoke the Heroku orb
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --exclude venv* --statistics
            pytest -v --cov=quado
      # Step 4: build docker images
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Build Docker image
          command: |
            docker build -t quado-frontend:circleci -f frontend/Dockerfile.web . 
            docker build -t quado-backend:circleci -f backend/Dockerfile.worker .  
            docker images
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - run:
          name: Storing previous commit
          command: |
            git rev-parse HEAD > ./commit.txt
      - heroku/install
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Pushing to heroku registry
          command: |
              heroku container:login 
              heroku container:push web worker --recursive --arg NODE_ENV=production -a $HEROKU_APP_NAME
              heroku container:release web worker -a $HEROKU_APP_NAME
workflows:
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy: # Use the pre-configured job, deploy-via-git
          requires:
            - build-and-test
          filters:
            branches:
              only: main
